### ISSUE TITLE
Problem with moving pages when ProcessPreview is installed

### ISSUE THREAD

**Issue by MichaelvanLaar** [nicoknoll/ProcessPreview#1]
With installed ProcessPreview the following happens (tested on two different installations):

After moving a page around in the page tree I can’t click any page name (well, of course I can click, but nothing happens) and have to press F5 for a reload before I can go on with any editing.

As soon as I uninstalled ProvessPreview moving pages worked as it should.

**Comment by nicoknoll** [comment]
Thanks for reporting. I'll have a look on it soon.

Greets,
Nico Knoll

http://nico.is/
http://www.stadtpirat.net/

Am 01.07.2012 um 19:58 schrieb Michael van Laar reply@reply.github.com:

**Comment by gerritvanaaken** [comment]
same here. Can’t figure out how to fix it!

**Comment by nicoknoll** [comment]
Should be fixed in 2.5.0 .
